### ISSUE TITLE
9 requests

### ISSUE THREAD

**Issue by wizarduk** [AaronClifford/nominet-ror-epp-software#10]
They are now raising the request limit to 9 will the system need updating now as discussed

**Comment by AaronClifford** [comment]
Will be added and released tomorrow AM, thanks Sam

**Comment by neilstanley** [comment]
Hi Aaron they have raised the limit to 12 for us.

**Comment by AaronClifford** [comment]
Hi Neil, the setup was originally made for six, I'll be releasing an update
with some bug fixes and will update where I can

**Comment by neilstanley** [comment]
Many thanks Aaron

**Comment by jon2014** [comment]
Hi Aaron, i'm getting "file_get_contents(../../domains/27-06-19.txt): failed to open stream: No such file or directory". Don't understand why it's trying to access that particular file as i've replaced it in the domains directory with one called 01-07-19.txt ? Thanks, Jon

**Comment by AaronClifford** [comment]
@jon2014 the script will look for a a domain list of the day you are running it on, so the error is due to it being ran on the 27-06-19 and it expects to find a script there.

**Comment by AaronClifford** [comment]
Added 9 requests

**Comment by 0219dives** [comment]
Great work thanks Aaron!
