### ISSUE TITLE
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41

### ISSUE THREAD

**Issue by meslam479** [AaronClifford/nominet-ror-epp-software#12]
Hi Aaron, I have done a final check before the release but got a new issue 

for the record, I have change epp to ror-epp.nominet.org.uk and dac to dac.nic.uk to be ready, changed create_requests to 9 

[root@centos-s-1vcpu-1gb-lon1-01 ~]# cd nominet-ror-epp-software
[root@centos-s-1vcpu-1gb-lon1-01 nominet-ror-epp-software]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-30 11:50:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:51:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:52:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:53:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:54:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:55:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:56:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:57:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:58:00.000
MESSAGE: Domain: k.uk (Available for next minute) 
MESSAGE: Domain: z.uk (Available for next minute) 
MESSAGE: Domain: voice.uk (Available for next minute) 
MESSAGE: Domain: ff.uk (Available for next minute) 
MESSAGE: Domain: law.uk (Available for next minute) 
MESSAGE: Domain: btc.uk (Available for next minute) 
MESSAGE: Domain: job.uk (Available for next minute) 
MESSAGE: Domain: vip.uk (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-30 11:59:00.000
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
PHP Notice:  Undefined offset: 1 in /root/nominet-ror-epp-software/app/Nominet/Dac.php on line 41
---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting

Log file attached

[30-06-19-EPP.txt](https://github.com/AaronClifford/nominet-ror-epp-software/files/3342839/30-06-19-EPP.txt)

**Comment by meslam479** [comment]
It's working when changing create_requests to 6

**Comment by AaronClifford** [comment]
I'll have a look later today and let you know if I have any questions

**Comment by meslam479** [comment]
Ok, thanks Aaron, I owe you bigtime

**Comment by AaronClifford** [comment]
Just waiting for my IP to update on the live ROR system so I can check for you and I'll get back to you

**Comment by AaronClifford** [comment]
It looks like your DAC connection disconnects, do you have a scripts running elsewhere, as there can only be a max of four connections at one time on the DAC, any chance that's disconnecting it?

**Comment by AaronClifford** [comment]
I've just ran a test on a list on names, for over 6 minutes, settings on 9 without issue, can't seem to replicate?

**Comment by meslam479** [comment]
Ok, I have my catching system working, will turn it off and test again now

**Comment by meslam479** [comment]
Thanks Aaron, It's working fine, seems like I will have to stop catching .co.uk domains till .uk release finish.

**Comment by AaronClifford** [comment]
Great news glad it's now working
