### ISSUE TITLE
Domains registered for 2 years

### ISSUE THREAD

**Issue by kualojo** [AaronClifford/nominet-ror-epp-software#13]
Firstly thanks for an excellent solution for this. When we ran this today we found that the domains which were successfully registered were for a period of 2 years.

This appears to be the default value.

I think it may be useful to update the EPP code to specify a 1 year registration, i.e.:

<domain:period unit="y">1</domain:period>

Unfortunately it is not possible to adjust domains now registered without de-registering them.

I suspect the majority of people using this script will likely wish to ensure registrations are for 1 year only.

**Comment by AaronClifford** [comment]
I'll resolve this and release for tomorrow. How did you do?

**Comment by kualojo** [comment]
Thanks Aaron, much appreciated. 

3.6% success rate with 12 requests per minute. Most of what we'd attempted to register was taken after ~2 minutes.

Insane.

**Comment by AaronClifford** [comment]
Released a patch to reduce this down to one year
