### ISSUE TITLE
Great tool registrant is the TAG holder

### ISSUE THREAD

**Issue by JimZAH** [AaronClifford/nominet-ror-epp-software#14]
Hi Aaron,
We used your tool today with great success so thank you. However we have found an issue when the domain has been created. The registrant is the TAG holder. Lets say for example our company is called bigdomains Ltd and our tag is bigdomains. When we create a new domain it's automatically setting the registrant as bigdomains Ltd with the contact details and address as per the EPP file. The contacts and address isn't an issue as we can change these without issue via Nominet. However they are really funny about changing the registrant, How can we set the registrant name? 

I can see the bit of code that creates the contact as below, however I'm not sure where this is called.
`function createContact($registrant, $name, $org)`

Sorry if I'm missing something obvious.

Kind Regards
Jim

**Comment by 0219dives** [comment]
Has anyone had any issues connecting to the Test EPP platform? Wondering if it's just my connection or whether it's currently down for everyone? Thanks Dan

**Comment by wizarduk** [comment]
The testbed epp is no longer active

**Comment by 0219dives** [comment]
Haha thanks @wizarduk that explains that then :P Cheers!
