### ISSUE TITLE
autoload error

### ISSUE THREAD

**Issue by JohnAJ** [AaronClifford/nominet-ror-epp-software#2]
First off - Thanks very much for this!

I don't have git installed (uploading to a web server running cPanel via FTP) so did as suggested and downloaded then uploaded all files, however I get an error on running: -

PHP Warning:  require(/home/xxxxxx/public_html/nominet-epp/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/xxxxxx/public_html/nominet-epp/app/bootstrap.php on line 2

Which I think is because I didn't install via git.....any help much appreciated!

**Comment by AaronClifford** [comment]
I'll have a version that can be uploaded without the need for composer tomorrow AM. It's not currently required but could be for the final version

**Comment by JohnAJ** [comment]
Thanks - it's on a WHM / cPanel reseller and I don't have shell access!

**Comment by wizarduk** [comment]
same issue with it installed...

**Comment by AaronClifford** [comment]
Update coming later 👍

**Comment by JohnAJ** [comment]
Much appreciated!

My host allowed me SSH access and composer was already installed, and so I don't need it as much as I did - but might help someone else!

Thanks again!

**Comment by AaronClifford** [comment]
Patch to come in the morning, need to get on my work pc in the morning!

**Comment by AaronClifford** [comment]
Autoload error fixed, still working on the EPP error, I believe its SSL related, fix to come this morning.
