### ISSUE TITLE
PHP Warning error

### ISSUE THREAD

**Issue by meslam479** [AaronClifford/nominet-ror-epp-software#3]
I got this issue when running command line php index.php

PHP Warning:  stream_get_contents() expects parameter 1 to be resource, boolean given in /root/nominet-ror-epp-software/app/Nominet/Epp.php on line 147

**Comment by AaronClifford** [comment]
Have you configured your EPP testbed IP and password, and put that in the config?

**Comment by meslam479** [comment]
Sure, I have configured it except for testRegistrantOrg as i don't have an organization/company name

**Comment by AaronClifford** [comment]
Update to come today.

**Comment by AaronClifford** [comment]
I now believe this is an error with Nominet updating the IPs on the testbed for a while. I'm running a test now, I have released some new code to catch this error, so if you could try running the new version and let me know the response.

**Comment by AaronClifford** [comment]
Issue now resolved, it's taking over an hour for the IP address to register with the testbed, I've also added a catch error for this. Please download and try again.

**Comment by meslam479** [comment]
Thanks Aaron it's working now in the centos server but still there is a little problem when creating domain but i think it's not from your code 

MESSAGE: EPP Connected
MESSAGE: Contact Created Successfully
Error creating domain name, please review the lastest log file.

log file shows <reason>V350 The operation would exceed the number of domains allowed on a self managed tag</reason>

I have spoken to nominet and they said error message is usually due to registering domain names to a contact which isn't a Connected Name on my Self-Managed Tag but I have double checked my contact name in config.php so they will investigate further and get back to me as soon as possible

**Comment by AaronClifford** [comment]
Put the same name you use in the registrants name as you do in the org, that worked for me

**Comment by AaronClifford** [comment]
You'll also have to change the registrant I'd (everytime you run the script)

**Comment by meslam479** [comment]
thanks Aaron it's working now
