### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dee7271** [AaronClifford/nominet-ror-epp-software#6]
Hi Aaron,

Just testing the new version. I had the old one working and think I've set config up okay

1/ How do you stop the run rather than have to quit terminal and ssh back in ?

2/I seem to be getting an error in logs. Im using domains from the ROR list. If i look at returned logs it seems to handshake okay but then i get:

```

10:16:05.0,¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2001">
      <msg>
        Command syntax error: error at line 12: Element '{urn:ietf:params:xml:ns:domain-1.0}name': [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'.
error at line 12: Element '{urn:ietf:params:xml:ns:domain-1.0}name': '' is not a valid value of the atomic type '{urn:ietf:params:xml:ns:eppcom-1.0}labelType'.
      </msg>
    </result>
    <trID>
      <svTRID>15537445209</svTRID>
    </trID>
  </response>


```

**Comment by AaronClifford** [comment]
Hi, if you want to cancel the script running in the terminal just hold CTRL+C that will cancel the script, can you show me the domain, do you have a blank line at the bottom of your domain file at all, that may be causing it?

**Comment by dee7271** [comment]
Hi Aaron

Definitely no blank at bottom of  txt file. Ive just checked

**Comment by dee7271** [comment]
using these domains from ROR list (random pick)

2-look.uk
2-mail.uk
2-makkah.uk
2-market.uk
2-md.uk
2-mindshorsesitting.uk
2-minute-web-site.uk
2-minute-website.uk
2-morrow.uk
2-nil.uk
2-obvious.uk
2-one.uk
2-p-microscopy.uk
2-prepare.uk
2-rc.uk
2-rent.uk

**Comment by dee7271** [comment]
And this is terminal output 

MESSAGE: EPP Connected
Next Run: 2019-06-21 10:58:00.000
MESSAGE: Domain:  (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-21 10:59:00.000
MESSAGE: Domain:  (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-21 11:00:00.000
terminatMESSAGE: Domain:  (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-21 10:01:00.000
e
MESSAGE: Domain:  (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-21 10:02:00.000
MESSAGE: Domain:  (Available for next minute) 
---------------------------------------------------------------------------
Next Run: 2019-06-21 10:03:00.000
MESSAGE: Domain:  (Available for next minute)

**Comment by AaronClifford** [comment]
What's the name of your file in the domains folder?

**Comment by dee7271** [comment]
Just as downloaded so

DD-MM-19.txt

**Comment by AaronClifford** [comment]
You need to change the DD-MM to the actual day and month so 21-06-19.txt, I'll update the readme to explain to others.

**Comment by dee7271** [comment]
Lol…..facepalm ! 

I just clicked that was probably it as i hit send. Thank you for you patience .

**Comment by dee7271** [comment]
Okay. Now i get  this, even though list has stuff in there. Apologies for all the messages

---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting
[root@vps-e3a593 EPP]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-21 11:34:00.000

**Comment by AaronClifford** [comment]
That's right, it will run on that minute (next minute after you start)

**Comment by AaronClifford** [comment]
Let me know what happens!

**Comment by dee7271** [comment]
Sorry... paste error

```
---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting
[root@vps-e3a593 EPP]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-21 11:43:00.000
---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting
[root@vps-e3a593 EPP]# 

```

So it seems to think domainlist is empty, or im reading output as wrong when its right. The list is in   domains/21-06-19.txt

and contains ( with no extra spaces or line breaks) :

2-mail.uk
2-makkah.uk
2-market.uk
2-md.uk
2-mindshorsesitting.uk
2-minute-web-site.uk
2-minute-website.uk
2-morrow.uk
2-nil.uk
2-obvious.uk
2-one.uk
2-p-microscopy.uk
2-prepare.uk
2-rc.uk
2-rent.uk

log file is:

`11:47:38.780,	ë<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <greeting>
    <svID>Nominet EPP server testbed-epp.nominet.org.uk</svID>
    <svDate>2019-06-21T10:47:33Z</svDate>
    <svcMenu>
      <version>1.0</version>
      <lang>en</lang>
      <objURI>http://www.nominet.org.uk/epp/xml/nom-abuse-feed-1.0</objURI>
      <objURI>http://www.nominet.org.uk/epp/xml/nom-reseller-1.0</objURI>
      <objURI>http://www.nominet.org.uk/epp/xml/nom-tag-1.0</objURI>
      <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
      <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
      <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>
      <svcExtension>
        <extURI>http://www.nominet.org.uk/epp/xml/contact-nom-ext-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/domain-nom-ext-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/domain-nom-ext-1.1</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/domain-nom-ext-1.2</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/nom-data-quality-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/nom-data-quality-1.1</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-contact-id-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-fork-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-handshake-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-list-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-locks-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-notifications-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-notifications-1.1</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-notifications-1.2</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-release-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-unrenew-1.0</extURI>
        <extURI>http://www.nominet.org.uk/epp/xml/std-warning-1.1</extURI>
        <extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>
        <extURI>urn:ietf:params:xml:ns:validate-0.1</extURI>
      </svcExtension>
    </svcMenu>
    <dcp>
      <access><all/></access>
      <statement>
        <purpose><admin/><prov/></purpose>
        <recipient><ours/></recipient>
        <retention><business/></retention>
      </statement>
    </dcp>
  </greeting>
</epp>
11:47:43.780,·<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="1000">
      <msg>
        Command completed successfully
      </msg>
    </result>
    <trID>
      <svTRID>15537566023</svTRID>
    </trID>
  </response>
</epp>
11:48:05.0,¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566655</svTRID>
    </trID>
  </response>
</epp>¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566480</svTRID>
    </trID>
  </response>
</epp>¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566481</svTRID>
    </trID>
  </response>
</epp>¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566656</svTRID>
    </trID>
  </response>
</epp>¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566658</svTRID>
    </trID>
  </response>
</epp>¯<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nominet.org.uk/epp/xml/epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2306">
      <msg>Parameter value policy error</msg>
      <extValue>
        <value>
          <domain:name
            xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
            xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd">
            2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk
          </domain:name>
        </value>
        <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk cannot be requested via this automaton</reason>
      </extValue>
    </result>
    <trID>
      <clTRID>abcde12345</clTRID>
      <svTRID>15537566659</svTRID>
    </trID>
  </response>
</epp>
`

**Comment by AaronClifford** [comment]
Ah, you've got a space after each domain by the looks of it which is causing it now to create the correct array of domains, I'll put a patch in for this now, but as you see from the below logs without spaces:

MESSAGE: EPP Connected
Next Run: 2019-06-21 11:53:00.000
MESSAGE: Domain: testsw1drsdrsrwerw.uk (Registered) (ADOMAINS)
MESSAGE: Domain: testsw2drsdrsrwerw.uk (Registered) (ADOMAINS)
MESSAGE: Domain: testsw3drsdrsrwerw.uk (Registered) (ADOMAINS)
MESSAGE: Domain: testsw4drsdrsrwerw.uk (Registered) (ADOMAINS)

**Comment by AaronClifford** [comment]
Infact, that doesn't seem correct, I've copied and pasted your domains in (added a character so I don't reg the test ones you are using) editing in notepad and it worked correctly:

MESSAGE: Domain: 12-mail.uk (Registered) (ADOMAINS)
MESSAGE: Domain: 22-makkah.uk (Registered) (ADOMAINS)
MESSAGE: Domain: 32-market.uk (Registered) (ADOMAINS)
MESSAGE: Domain: 42-md.uk (Registered) (ADOMAINS)
MESSAGE: Domain: 52-mindshorsesitting.uk (Registered) (ADOMAINS)
MESSAGE: Domain: 62-minute-web-site.uk (Registered) (ADOMAINS)

Can you try deleting the white spaces and adding them in again.

**Comment by dee7271** [comment]
Mmm…weird. There isnt though in my file. Its a direct copy from Robs csv download and there are no spaces after domains on line.

**Comment by AaronClifford** [comment]
Did you copy and paste in notepad?

**Comment by dee7271** [comment]
Im on a mac. Ill try directly on server.

**Comment by AaronClifford** [comment]
Can see from the logs there is some weird spacing:

 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk </domain:name> </value> <reason>V009 Domain 2-mail.uk 2-makkah.uk 2-market.uk 2-md.uk 2-mindshorsesitting.uk 2-minute-web-site.uk 2-minute-website.uk 2-morrow.uk 2-nil.uk 2-obvious.uk 2-one.uk 2-p-microscopy.uk 2-prepare.uk 2-rc.uk 2-rent.uk 

which isn't seperating the domains properly

**Comment by dee7271** [comment]
Wow… thanks again for all your help on this. Very strange.

I deleted back one from every line and returned again and now getting this

MESSAGE: Domain List Empty, Exiting
[root@vps-e3a593 EPP]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-21 12:05:00.000
MESSAGE: Domain: 2-mail.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-makkah.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-market.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-md.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-mindshorsesitting.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-minute-web-site.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-minute-website.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-morrow.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-nil.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-obvious.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-one.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-p-microscopy.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-prepare.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-rc.uk (Missed) (DROPCYCLE) 
MESSAGE: Domain: 2-rent.uk (Missed) (DROPCYCLE) 


So seems to be working thanks !  Weirdly though there was no ability to navigate/delete  through any spaces in the txt file. They certainly didnt look to be there with cursor

**Comment by AaronClifford** [comment]
Great, I can't account for additional white spaces or strange line breaks to always give it a test run before to make sure.
