### ISSUE TITLE
no generated log file for the test?

### ISSUE THREAD

**Issue by meslam479** [AaronClifford/nominet-ror-epp-software#9]
Hi Aaron,

after testing the new version, i don't see any file in logs? 

the test shown to me in console but there is no generated log file for the test

[root@centos-s-1vcpu-1gb-lon1-01 nominet-ror-epp-software]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-22 16:56:00.000
MESSAGE: Domain: d-associates.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-b-w.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-barfield.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-barnett.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-barrow.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-basics.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-beauty.uk (Missed) (NETPRESTO) 
MESSAGE: Domain: d-bell.uk (Missed) (NETPRESTO) 
---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting

**Comment by AaronClifford** [comment]
I'll have a test run tomorrow and let you know if I can replicate it

**Comment by AaronClifford** [comment]
I'm seeing logs, can you check the file permissions and make sure the folder logs is in the directory?

**Comment by meslam479** [comment]
Thanks, Aaron I can see all logs now, I don't know why but I have checked today and found logs from 22-06-19-EPP to 25-06-19-EPP - funny the folder was empty yesterday 😃

Can you please check 24-06-19-EPP logs that I have attached and let me know if there is any problem you can notice?

Thanks again for your time 

[24-06-19-EPP.txt](https://github.com/AaronClifford/nominet-ror-epp-software/files/3325296/24-06-19-EPP.txt)

**Comment by AaronClifford** [comment]
It all looks correct,the problem is Nominet have reserved all the domains again and aren't currently running tests. try a name like sdfasdtfd-gdfsg1231.uk and it should register as it's not under RoR.

**Comment by meslam479** [comment]
I have tried sdfasdtfd-gdfsg1231.uk but getting V350 The operation would exceed the number of domains allowed on a self managed tag

[25-06-19-EPP.txt](https://github.com/AaronClifford/nominet-ror-epp-software/files/3325395/25-06-19-EPP.txt)

**Comment by AaronClifford** [comment]
What registrant ID are you using? need to make sure you are using the one you created with the test create, and using that in the live id config.

**Comment by meslam479** [comment]
Ok, I have done that, I'm getting success message in console

[root@centos-s-1vcpu-1gb-lon1-01 nominet-ror-epp-software]# php index.php
MESSAGE: EPP Connected
Next Run: 2019-06-25 14:40:00.000
MESSAGE: Domain: sdfasdtfd-gsgj1-231.uk (Registered) (my tag)
---------------------------------------------------------------------------
MESSAGE: Domain List Empty, Exiting

[25-06-19-EPP.txt](https://github.com/AaronClifford/nominet-ror-epp-software/files/3325530/25-06-19-EPP.txt)

**Comment by AaronClifford** [comment]
That's correct, let me know if you have any more problems!
